Update tint2-session

diff --git a/install_tint2/tint2-session b/install_tint2/tint2-session
--- a/install_tint2/tint2-session
+++ b/install_tint2/tint2-session
@@ -1,27 +1,46 @@
 #!/bin/bash
-# Start or restart all tint2 configs saved in session file
+# Manage tint2 session file and stop, start and restart tint2 configs
 
 session_file="$HOME/.config/tint2/tint2-sessionfile"
 default_tint="$HOME/.config/tint2/tint2rc"
 
 # CHECK SESSION FILE
-if [ ! -s "$session_file" ]; then
-	if [ ! -s "$default_tint" ]; then
-		echo "Tint2 session file or default tint not found!"
-		exit 1
+function check_sessionfile() {
+	if [ ! -s "$session_file" ]; then
+		if [ ! -s "$default_tint" ]; then
+			echo "Tint2 session file or default tint not found!"
+			exit 1
+		fi
+
+		echo "Creating tint2 session file $session_file with default tint2rc config"
+		echo "$default_tint" > "$session_file"
 	fi
-	
-	echo "Creating tint2 session file $session_file with default tint2rc config"
-	echo "$default_tint" > "$session_file"
-	exit 1
-fi
+}
 
 # KILL CURRENT TINT2
-killall tint2
-killall -9 tint2
+function stop() {
+	killall tint2
+	killall -9 tint2
+}
 
 # EXEC SESSION TINTS
-IFS=$'\n'
-while read t; do 
-	(setsid tint2 -c "$t" &)
-done < "$session_file"
+function start() {
+	local IFS=$'\n'
+	while read t; do 
+		(setsid tint2 -c "$t" &)
+	done < "$session_file"
+}
+
+
+case "${1,,}" in
+	""|start|restart)
+		check_sessionfile
+		stop
+		start		
+	;;
+	stop)
+		stop
+	*)
+	
+	;;
+esac
